### ISSUE TITLE
Subscribe to service update

### ISSUE THREAD

**Issue by edigiacomo** [edigiacomo/django-statusboard#10]
User can subscribe to service updates. The app will send an email when the status changes.

**Comment by brancomat** [comment]
strongly imho:

"service updates" might be a simple notification for a change of status of a single service, excluding passages from operative to performance issues (or viceversa) that are not noteworthy.

I'd also exclude details about incidents: the e-mail should be a mere notification that triggers some human  follow-up (starting from the statuspage url)

since this is a peculiar point of view (at best) maybe incident notification could be set as an option

**Comment by edigiacomo** [comment]
I close this issue for the [same reason I closed #35](https://github.com/edigiacomo/django-statusboard/issues/35#issuecomment-285348040)
